### ISSUE TITLE
Firefox 4 issue

### ISSUE THREAD

**Issue by moosetoga** [individual11/Placehold.it-JQuery-plugin#2]
Works great in all browsers I've tested (IE 9, Chrome 11, Safari 5, Opera 11) except for Firefox 4, where for some reason the dimensions in the generated URL are incorrect. 

The dimensions of the image in question are 119x145. In all other browsers the img tag is generated like so:

```
http://placehold.it/119x145/f3f1f1/999999.gif&text=NO%20PHOTO
```

While in Firefox it's:

```
http://placehold.it/39x15/f3f1f1/999999.gif&text=NO PHOTO
```

**Comment by individual11** [comment]
Trying to track it down. You on mac or PC? Can't seem to duplicate on mac in FF 4.0.1 at the moment, but if you have URL, can look directly. (am seeing a jquery error however in it, so looking into that as well, but that's for the .error function)

**Comment by individual11** [comment]
Actually going to close this thread down since it's a dupe. meant to a minute ago, and lost track of which thread I was in. The one is that is open is [here](https://github.com/individual11/Placehold.it-JQuery-plugin/issues/1).
